# Generated by Django 5.0.6 on 2024-06-27 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_rename_addressbook_address'),
        ('file_upload', '0003_rename_image_uploadedimage_file'),
        ('meals', '0004_setmealdish_name_setmealdish_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('status', models.IntegerField(choices=[(1, 'unpaid'), (2, 'unaccepted'), (3, 'accepted'), (4, 'distributing'), (5, 'completed'), (6, 'canceled')], default=1)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('checkout_time', models.DateTimeField(blank=True, null=True)),
                ('pay_method', models.IntegerField(choices=[(1, 'wechat'), (2, 'alipay')])),
                ('pay_status', models.IntegerField(choices=[(1, 'unpaid'), (2, 'paid'), (3, 'refunded')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=32)),
                ('consignee', models.CharField(max_length=32)),
                ('cancel_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('cancel_time', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_status', models.IntegerField(choices=[(1, 'rightnow'), (0, 'adapt delivery time')])),
                ('delivery_time', models.DateTimeField(blank=True, null=True)),
                ('pack_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tableware_number', models.IntegerField()),
                ('tableware_status', models.IntegerField(choices=[(1, 'yes'), (0, 'no')])),
                ('address_book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.address')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.wechatcostomer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('dish_flavor', models.CharField(blank=True, max_length=32, null=True)),
                ('number', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dish_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meals.dish')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_upload.uploadedimage')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('setmeal_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meals.setmeal')),
            ],
        ),
    ]
