# Generated by Django 5.0.6 on 2024-06-18 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file_upload', '0003_rename_image_uploadedimage_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='category name')),
                ('type', models.IntegerField(choices=[(1, 'meal category'), (2, 'setmeal category')], verbose_name='category type')),
                ('sort', models.IntegerField(unique=True, verbose_name='sort order')),
                ('status', models.IntegerField(choices=[(1, 'activated'), (0, 'banned')], default=1, verbose_name='status')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Last Update Time')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_category', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_category', to=settings.AUTH_USER_MODEL, verbose_name='Last Update User')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='dish name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('status', models.IntegerField(choices=[(1, 'activated'), (0, 'banned')], default=1, verbose_name='status')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Last Update Time')),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meals.category', verbose_name='category')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dish', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file_upload.uploadedimage', verbose_name='image')),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_dish', to=settings.AUTH_USER_MODEL, verbose_name='Last Update User')),
            ],
        ),
        migrations.CreateModel(
            name='DishFlavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='flavor name')),
                ('value', models.CharField(max_length=255, verbose_name='flavor value')),
                ('dish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.dish', verbose_name='dish')),
            ],
        ),
        migrations.CreateModel(
            name='Setmeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='setmeal name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('status', models.IntegerField(choices=[(1, 'activated'), (0, 'banned')], default=1, verbose_name='status')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Last Update Time')),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meals.category', verbose_name='category')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_setmeals', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file_upload.uploadedimage', verbose_name='image')),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_setmeals', to=settings.AUTH_USER_MODEL, verbose_name='Last Update User')),
            ],
        ),
        migrations.CreateModel(
            name='SetmealDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copies', models.IntegerField()),
                ('dish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.dish')),
                ('setmeal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.setmeal')),
            ],
        ),
    ]
