# Generated by Django 5.0.6 on 2024-06-18 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_rename_category_id_dish_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='dishflavor',
            old_name='dish',
            new_name='dish_id',
        ),
        migrations.RenameField(
            model_name='setmeal',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='setmealdish',
            old_name='dish',
            new_name='dish_id',
        ),
        migrations.RenameField(
            model_name='setmealdish',
            old_name='setmeal',
            new_name='setmeal_id',
        ),
    ]
