version: "3.8"

services:
  web:
    build: .
    ports: 
      - "8080:8080"
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - MYSQL_NAME=${MYSQL_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
    
  db:
    image: mysql:latest
    volumes:
      - mysql_db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  redis:
    image: redis:latest

  rocketmq-namesrv:
    image: apache/rocketmq:latest
    container_name: rocketmq-namesrv
    command: sh mqnamesrv

  rocketmq-broker:
    image: apache/rocketmq:latest
    container_name: rocketmq-broker
    depends_on:
      - rocketmq-namesrv
    # volumes:
    #   - ./rocketmq-broker.conf:/etc/rocketmq/broker.conf
    command: sh mqbroker -n rocketmq-namesrv:9876 
    environment:
      - JAVA_OPT_EXT=-server -Xms512M -Xmx512M -Xmn256M
      - NAMESRV_ADDR=rocketmq-namesrv:9876

volumes:
  mysql_db_data: