# Generated by Django 5.0.6 on 2024-06-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_create_user_employee_update_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='sex',
            field=models.IntegerField(blank=True, choices=[('M', 'male'), ('F', 'female')], null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.IntegerField(blank=True, choices=[('N', 'normal'), ('L', 'locked')], default=1, null=True, verbose_name='Account Status'),
        ),
    ]
