# Generated by Django 5.0.6 on 2024-06-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'normal'), (0, 'locked')], default='N', null=True, verbose_name='Account Status'),
        ),
    ]
