# Generated by Django 5.0.6 on 2024-06-17 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employee_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='create_time',
            new_name='createTime',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='create_user',
            new_name='createUser',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='update_time',
            new_name='updateTime',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='update_user',
            new_name='updateUser',
        ),
    ]
