# Generated by Django 5.0.6 on 2024-06-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_rename_create_time_employee_createtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'normal'), (0, 'locked')], default=1, null=True, verbose_name='Account Status'),
        ),
    ]
