# Generated by Django 5.0.6 on 2024-06-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_alter_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='sex',
            field=models.CharField(blank=True, choices=[('1', 'male'), ('0', 'female')], max_length=1, null=True),
        ),
    ]
