# Generated by Django 5.0.6 on 2024-06-18 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0002_rename_upload_at_uploadedimage_uploaded_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedimage',
            old_name='image',
            new_name='file',
        ),
    ]
