# Generated by Django 5.0.6 on 2024-06-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_sex_alter_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, choices=[('N', 'normal'), ('L', 'locked')], default=1, max_length=1, null=True, verbose_name='Account Status'),
        ),
    ]
