# Generated by Django 5.0.6 on 2024-06-18 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedimage',
            old_name='upload_at',
            new_name='uploaded_at',
        ),
    ]
