# Generated by Django 5.0.6 on 2024-06-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_sex_alter_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, choices=[('N', 'normal'), ('L', 'locked')], default='N', max_length=1, null=True, verbose_name='Account Status'),
        ),
    ]
