# Generated by Django 5.0.6 on 2024-06-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_rename_category_dish_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setmealdish',
            name='name',
            field=models.CharField(default='', max_length=32, verbose_name='dish name'),
        ),
        migrations.AddField(
            model_name='setmealdish',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='price'),
        ),
    ]
